// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import models "github.com/felipe_rodrigues/poll-api/pkg/domain/models"

// VoteRepository is an autogenerated mock type for the VoteRepository type
type VoteRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, vote
func (_m *VoteRepository) Create(ctx context.Context, vote models.Vote) (models.Vote, error) {
	ret := _m.Called(ctx, vote)

	var r0 models.Vote
	if rf, ok := ret.Get(0).(func(context.Context, models.Vote) models.Vote); ok {
		r0 = rf(ctx, vote)
	} else {
		r0 = ret.Get(0).(models.Vote)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.Vote) error); ok {
		r1 = rf(ctx, vote)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
